spring:
  cloud:
    nacos:
      discovery:
        #指定nacos server的地址
        server-addr: localhost:8848
  application:
    #服务名称（尽量用-，不要用_，更不要用特殊字符）
    name: service-a

logging:
  level:
    com.jyannis.servicea.feignclient.ServiceBFeignClient: debug

feign:
  client:
    config:
      # 要调用的微服务的名称
      service-b:
        loggerLevel: FULL

server:
  port: 8181


